# Generated by Django 4.2.4 on 2023-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.CharField(max_length=20),
        ),
    ]
