# Generated by Django 4.2.4 on 2023-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_tarea_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
    ]
